# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1axlQAMPSgFxVznle0CkKQOkzkoRQxusX
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import pickle

dataset = pd.read_csv('salary_data.csv')

dataset.head(5)

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values


from sklearn.linear_model import LinearRegression
regressor = LinearRegression()

regressor.fit(X,y)

pickle.dump(regressor,open('model.pkl','wb'))

